local_costmap:
   global_frame: known_map
   robot_base_frame: robot0
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: true
   rolling_window: true
   width: 5.0
   height: 5.0
   resolution: 0.05
   transform_tolerance: 0.5
   plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}